version: '3'

services:
  app:
    build: .
    command: npm run start
#    command: tail -f /dev/null
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - APP_HOST=app
      - localhost=db
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-files/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
       - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:1.19
    volumes:
      - ./docker-files/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  db_data: {}